// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDobtP3tdWQ3AqmA0KuF1LtewKRaHe5YwY',
    appId: '1:467827529043:android:07bcf032159bf45f1b3da6',
    messagingSenderId: '467827529043',
    projectId: 'dinoapp-8e72f',
    databaseURL: 'https://dinoapp-8e72f-default-rtdb.firebaseio.com',
    storageBucket: 'dinoapp-8e72f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWYqTSlKrHTlwlkn_mwbUoFcMVetu4t20',
    appId: '1:467827529043:ios:7ae7408bb5cca81f1b3da6',
    messagingSenderId: '467827529043',
    projectId: 'dinoapp-8e72f',
    databaseURL: 'https://dinoapp-8e72f-default-rtdb.firebaseio.com',
    storageBucket: 'dinoapp-8e72f.appspot.com',
    iosBundleId: 'com.example.dinoApp',
  );
}
